nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_methods: []
        allow_headers: []
        expose_headers: ['Link']
        max_age: 0
        origin_regex: true
        forced_allow_origin_value: ~
    paths:
        '^/api/':
            allow_origin: ['%env(CORS_ALLOW_ORIGIN_BACKEND)%']
            allow_headers: ['Content-Type', 'Authorization','X-Requested-With']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            max_age: 3600